### ISSUE TITLE
能否添加过滤盐选专栏和Live讲座的功能

### ISSUE THREAD

**Issue by fuhan666** [dyingsunlight/tampermonkey#1]
收费且不实用。

**Comment by dyingsunlight** [comment]
https://greasyfork.org/zh-CN/scripts/397909-%E8%BF%87%E6%BB%A4%E7%9F%A5%E4%B9%8E%E4%B8%A5%E9%80%89-zhihu-yanxuan
可以直接过滤知乎回答里的付费栏目。另外Live讲座好像没有看到过，不知道是不是我装了 ADblock 过滤了
